# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4c62a9030c43111dbc3aaaf327ee86cc"
name = "qr-code-genarator"
handle = "qr-code-genarator"
application_url = "https://adapter-cake-dream-overhead.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-07987cf7.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://adapter-cake-dream-overhead.trycloudflare.com/auth/callback",
  "https://adapter-cake-dream-overhead.trycloudflare.com/auth/shopify/callback",
  "https://adapter-cake-dream-overhead.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
